items_per_page: 10
pagination_window: 10
language: en
og_locale: en_US
site_base_url: https://8sun.github.io
site_name: Бодхисаттва в сети
site_description: Нео-философская школа сдержек и противовесов ордена Брюса Ли
home_page_name: Дом